### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by 0PK** [matrix-io/matrixio-kernel-modules#14]
make -C /lib/modules/4.14.21-v7+/build M=/home/pi/matrixio-kernel-modules modules
make[1]: Entering directory '/lib/modules/4.14.21-v7+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.14.21-v7+/build'
Makefile:17: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eljuguetero** [comment]
This modules has been tested in Strech with kernel **4.9.59-v7+**

To revert the kernel version
` sudo apt-get install --reinstall raspberrypi-kernel `
` sudo reboot `

you should  sure you have the headers for compiling modules
` sudo apt-get  install raspberrypi-kernel-headers raspberrypi-kernel` 

BR 
-- afc

**Comment by Ultchad** [comment]
I have the same problem with Strech kernel 4.14.26-v7+:

```bash
make -C /lib/modules/4.14.26-v7+/build M=/home/pi/matrixio-kernel-modules modules
make[1]: *** /lib/modules/4.14.26-v7+/build: No such file or directory.  Stop.
Makefile:17: recipe for target 'all' failed
make: *** [all] Error 2
```
I think it's after 
```bash
rpi-update
```
i down kernel with rpi-update and the  [commit ID of kernel 4.9](https://github.com/Hexxeh/rpi-firmware/tree/5c80565c5c0c7f820258c792a98b56f22db2dd03) ( Find all commit [here](https://github.com/Hexxeh/rpi-firmware/commits/master) page )
```bash
sudo rpi-update 5c80565c5c0c7f820258c792a98b56f22db2dd03
```
And this compile and install :)

**Comment by kdpatino** [comment]
Hello @Ultchad 

Thank You for your feedback! I will add kernel information in the README, in order to be more clear about the proper environment.

Regards,

Kevin Patino

**Comment by anthonymicallef** [comment]
Even after downgrading to kernel 4.9.57-v7+, I still get Error 2:

> dtc -W no-unit_address_vs_reg -@ -I dts -O dtb -o matrixio.dtbo matrixio-overlay.dts
> make -C /lib/modules/4.9.57-v7+/build M=/home/pi/matrixio-kernel-modules modules
> make[1]: *** /lib/modules/4.9.57-v7+/build: No such file or directory.  Stop.
> Makefile:18: recipe for target 'all' failed
> make: *** [all] Error 2

What can I do to fix this?
