### ISSUE TITLE
asound.conf for Matrix Voice

### ISSUE THREAD

**Issue by nodered** [matrix-io/matrixio-kernel-modules#16]
I noticed the new .asoundrc file to be used with the kernel modules at https://github.com/matrix-io/matrixio-kernel-modules/blob/master/misc/asoundrc ...Do you have a new /etc/asound.conf as well?

Just saw a comment in the forums...no need for the asound.conf...?

**Comment by kdpatino** [comment]
Hello @nodered , Thank You for your feedback. Yes, we are working on a new release and it will fix this issue. I will let you know when we complete it.

**Comment by nodered** [comment]
I made an image today with raspbian stretch light, the kernel modules, sox and snowboy.
It’s just a start but something like this might make it faster/easier for people to get going. I think they call it ‘Onboarding’ now. It’s only 2GB so it’s quick download and burn.

https://drive.google.com/open?id=1AAVTsoHEOwQvT1hpvIBMKmyn1j7TyBZE

I am now just using /etc/asound.conf and this conf is working for me.  Any ideas on why mmap_emul
would be more stable?

pcm.!default {
    type asym
    capture.pcm "mic"
    playback.pcm "speaker"
}


pcm.mic {
   type softvol

   min_dB       -1.0
   max_dB       50.0

   slave {
     pcm "mmap0"
   }
   control {
     name "MicArray Master"
        card 0
   }
}



pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.mmap0 {
  type mmap_emul
    slave {
    pcm "hw:2,0"
  }
}

**Comment by kdpatino** [comment]
Hello,

We remove the asound.conf in the  **matrix-creator-init** package. Now, we are working on the Debian package for the kernel modules. 

Meanwhile, you could use: https://github.com/matrix-io/matrixio-kernel-modules/blob/master/misc/asound.conf

**Comment by Romkabouter** [comment]
Your image works great, no ambient distorted noise.
I will use this as a base, many thanks

**Comment by nodered** [comment]
Just so that you know, the kernel modules in that image do not work with pulseaudio.
