### ISSUE TITLE
Noise when recording

### ISSUE THREAD

**Issue by Romkabouter** [matrix-io/matrixio-kernel-modules#22]
Hi, I have the kernel modules installed on a pi with raspbian stretch.
I have found the recordings having distorted background noise. 
This is the case with arecord AND pyadio.
I have used the same code with an USB mic and the quality is much better, that is to say, only my voice is recorded and now skreaking background is heard.

Is there a way to get a cleaner output?

PS: I have MalOS NOT installed, so there is no interference from that part

**Comment by nodered** [comment]
I had the same problem when I installed the new kernel modules the other day.  I commented out the dummy sound module from /etc/modules-load.d/matrix-mics.conf ...rebooted and the sound was clean again?  This will change the array/card index number (hw:X,0) so if you have /etc/asound.conf or /home/pi/.asoundrc you will have to edit those after the change.

I don't know why this fixes the noise issue? Anyone?

**Comment by Romkabouter** [comment]
Good find, I will try that as well

**Comment by Romkabouter** [comment]
Unfortunatly, did not help. I think I did not have these issues when using HAL, I will try it to check if this is hardware related

**Comment by nodered** [comment]
I'm using the Matrix Voice and disabled some of the kernel modules, currently I just have the following modules loading at boot.
matrixio_pcm
matrixio_codec
matrixio_uart
matrixio_core

I was curious about the install process for those that have the Matrix Voice, does it matter if the Matrix Creator modules are also loaded?

**Comment by eljuguetero** [comment]
Hi,
We just found a bug in the kernel overlay file.
please run:

```
sudo apt-get update
sudo apt-get upgrade
```
then
```
sudo reboot
```

BR

**Comment by Romkabouter** [comment]
I have just tested this with a clean stretch install and kernel install (not building from source)
The noise is gone, so for me this issue can be closed
