### ISSUE TITLE
Installing modules on clean system

### ISSUE THREAD

**Issue by Romkabouter** [matrix-io/matrixio-kernel-modules#25]
When installing the kernel modules on a clean system, they are not put into /etc/modules.
Add this:

echo "matrixio-everloop" | sudo tee -a /etc/modules

Otherwise you will get permission denied errors when trying to control the everloop from python (for example)

**Comment by eljuguetero** [comment]
@Romkabouter 

After the `matrixio-kernel-modules` raspbian package installation the matrix modules for automatic loading are listed in `/etc/modules-load.d/matrixio.conf`.

The old school `/etc/modules` still untouched 

About `matrixio-kernel-modules`  installation from  reasbian packages:
[https://github.com/matrix-io/matrixio-kernel-modules#option-1-package-installation](https://github.com/matrix-io/matrixio-kernel-modules#option-1-package-installation)

**Comment by eljuguetero** [comment]
[](https://github.com/matrix-io/matrixio-kernel-modules#option-1-package-installation)

- [ ]
