### ISSUE TITLE
Unable to make backup link of './boot/overlays/matrixio.dtbo' before installing new version: Operation not permitted.

### ISSUE THREAD

**Issue by luc2yj** [matrix-io/matrixio-kernel-modules#27]
Any idea of what's going on? How should I solve this? 

[How it happened]
I failed to upgrade the kernel module. So I removed it and then tried to reinstall it. 

[Error code] from running 'sudo apt-get install matrixio-kernel-modules'
Preparing to unpack .../matrixio-kernel-modules_0.1-3_armhf.deb ...
Unpacking matrixio-kernel-modules (0.1-3) ...
dpkg: error processing archive /var/cache/apt/archives/matrixio-kernel-modules_0.1-3_armhf.deb (--unpack):
 unable to make backup link of './boot/overlays/matrixio.dtbo' before installing new version: Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/matrixio-kernel-modules_0.1-3_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by nodered** [comment]
I have had the same problem when 'reinstalling' the modules.

I fixed it by doing this before the install...
sudo mv /boot/overlays/matrixio.dtbo /boot/overlays/matrixioold.dtbo

**Comment by kdpatino** [comment]
Great!
