### ISSUE TITLE
raspi-snips-setup works with usb-headset, but not with matrix voice

### ISSUE THREAD

**Issue by toby2018** [matrix-io/matrixio-kernel-modules#38]
Hi,

as mentioned in the title, play and record works fine with usb-headset, but I'm not able to get the matrix voice involved correctly.
Help highly appreciated.

Thx Steffen

pi@assi:~ $ aplay -l
**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: ALSA [bcm2835 ALSA], Gerät 0: bcm2835 ALSA [bcm2835 ALSA]
  Sub-Geräte: 7/7
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
Karte 0: ALSA [bcm2835 ALSA], Gerät 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: Dummy [Dummy], Gerät 0: Dummy PCM [Dummy PCM]
  Sub-Geräte: 8/8
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
  Sub-Gerät #7: subdevice #7
Karte 2: headset [Sennheiser USB headset], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

pi@assi:~ $ arecord -l
**** Liste der Hardware-Geräte (CAPTURE) ****
Karte 1: Dummy [Dummy], Gerät 0: Dummy PCM [Dummy PCM]
  Sub-Geräte: 8/8
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
  Sub-Gerät #7: subdevice #7
Karte 2: headset [Sennheiser USB headset], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 0/1
  Sub-Gerät #0: subdevice #0
pi@assi:~ $ 

This version works fine w/ usb-headset.
When changing capture.pcm to "hw:1,0", it does not...
pi@assi:~ $ cat /etc/asound.conf
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
}
pi@assi:~ $

**Comment by samreenislam** [comment]
This issue has been solved on the community: https://community.matrix.one/t/matrix-voice-modul-considered-as-dummy-and-does-not-record/2426
