### ISSUE TITLE
Can't play from the matrix voice audio jack

### ISSUE THREAD

**Issue by nilicohen** [matrix-io/matrixio-kernel-modules#43]
Hello,

I try to play a wav file by the sound card of matrix voice.
I changed the default sound card in the audio settings to be MATRIXIO-SOUND (Alsa mixer).
Then, I try to play it with the following command:
aplay filename.wav

I get this error (no sound):
aplay: main:828: audio open error: No such file or directory

When the sound card of the raspberry pi, there is no error and it sound the file from its jack.

Is anybody experienced this kind of error?

**Comment by samreenislam** [comment]
Hi @nilicohen,

Apologies for the delayed response here. When you type `aplay -l` in your terminal, does the MATRIXIO-SOUND card show up as card 2, device 1?

If so, try setting your `/etc/asound.conf` to have the following line in `pcm.speaker` section:
```
pcm.speaker {
  type plug
  slave {
    pcm "plughw:2,1"
    rate 44100
  }
}
```
Then test by playing any soundtrack: `aplay recording.wav`.

Let me know how it goes!

Best,
Samreen
