### ISSUE TITLE
Compiling 0.2.1 fails on stretch

### ISSUE THREAD

**Issue by willamowius** [matrix-io/matrixio-kernel-modules#45]
I cloned the git repository and compiling the latest code fails on Raspberian stretch. V 0.1.9 compiles fine.

make -C /lib/modules/4.19.66-v7+/build M=/usr/src/matrixio-kernel-modules-0.2.1 modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.66-v7+'
  CC [M]  /usr/src/matrixio-kernel-modules-0.2.1/matrixio-core.o
  CC [M]  /usr/src/matrixio-kernel-modules-0.2.1/matrixio-uart.o
  CC [M]  /usr/src/matrixio-kernel-modules-0.2.1/matrixio-everloop.o
  CC [M]  /usr/src/matrixio-kernel-modules-0.2.1/matrixio-codec.o
  CC [M]  /usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.o
/usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.c:52:14: error: initializer element is not constant
  .rate_min = matrixio_params[0].rate,
              ^~~~~~~~~~~~~~~
/usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.c:52:14: note: (near initialization for ‘matrixio_pcm_capture_hw.rate_min’)
/usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.c:53:14: error: initializer element is not constant
  .rate_max = matrixio_params[ARRAY_SIZE(matrixio_params)-1].rate,
              ^~~~~~~~~~~~~~~
/usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.c:53:14: note: (near initialization for ‘matrixio_pcm_capture_hw.rate_max’)
cc1: warning: unrecognized command line option ‘-Wno-missing-attributes’
scripts/Makefile.build:309: recipe for target '/usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.o' failed
make[2]: *** [/usr/src/matrixio-kernel-modules-0.2.1/matrixio-mic.o] Error 1
Makefile:1519: recipe for target '_module_/usr/src/matrixio-kernel-modules-0.2.1' failed

**Comment by eljuguetero** [comment]
Fixed in v0.2.2
